version: 0.1
phases:
  install:
    commands:
      - npm install
      - ls -a
      - cat samTemplate.yaml
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket graphql-api-1
                                   --output-template-file outputSamTemplate.yaml
      - ls -a
      - cat outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml