version: 0.1

phases:
  install:
    commands:
      - npm i -g serverless
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - npm install
      - echo "dependencies install completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - serverless deploy -v --region=us-east-2
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - outputSamTemplate.yaml
  discard-paths: yes