version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket https://s3.us-east-2.amazonaws.com/graphql-api-1
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml