version: 0.1
phases:
  pre_build:
    commands:
      - cd app && npm install

  build:
    commands:
      - cat samTemplate.yaml
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket graphql-api-1
                                   --output-template-file outputSamTemplate.yaml
      - ls -a
      - cat outputSamTemplate.yaml
artifacts:
  discard-paths: yes
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml