AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - beta
      - gamma
      - prod
    Default: beta
    Description: Stage that can be added to resource names
Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.graphqlHandler
      Runtime: nodejs8.10
      CodeUri: app/
      Policies: AWSLambdaBasicExecutionRole
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: get
        PostRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
  GraphQLInspector:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.graphiqlHandler
      Runtime: nodejs8.10
      CodeUri: app/
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /graphiql
            Method: get