service: graphql-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod

functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          path: /graphql
          method: get
      - http:
          path: /graphql
          method: post
  graphiql:
    handler: handler.graphiqlHandler
    events:
      - http:
          path: /graphiql
          method: get

plugins:
   - serverless-offline