service: graphql-api

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"


functions:
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          path: /graphql
          method: get
      - http:
          path: /graphql
          method: post
  graphiql:
    handler: handler.graphiqlHandler
    events:
      - http:
          path: /graphiql
          method: get

plugins:
   - serverless-offline